services:
  api1: &api
    restart: always
    container_name: api1
    build: .
    ports:
      - "80"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./profiling:/app/profiling
    working_dir: /app
    environment:
      - POSTGRES_USER=afastapi
      - POSTGRES_PASSWORD=afastapi
      - POSTGRES_DB=afastapi
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PROFILER_PATH=/app/profiling
      - PROFILER_MODE=cpu
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '512MB'
  api2:
    <<: *api
    container_name: api2
  lb:
    container_name: lb
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128MB'
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=afastapi
      - POSTGRES_PASSWORD=afastapi
      - POSTGRES_DB=afastapi
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U afastapi" ]
      interval: 5s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1GB'
