@apiURL = http://localhost:9999
@jsonContentType = application/json

###

POST {{apiURL}}/people
Content-Type: {{jsonContentType}}

{
    "nickname": "josé{{$randomInt 1 1000}}{{$timestamp}}",
    "name": "José Roberto",
    "birthdate": "2000-10-01",
    "stack": ["C#", "Node", "Oracle"]
}

###
# @prompt id
GET {{apiURL}}/people/{{id}}


###

GET {{apiURL}}/count-people

### Valid request while using term search

# @prompt term
GET {{apiURL}}/people?t={{term}}

### Invalid request while using term search

GET {{apiURL}}/people?t=
