// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package people

import (
	"database/sql"
	"time"
)

type Person struct {
	ID         string
	Nickname   string
	Name       string
	Birthdate  time.Time
	Stack      sql.NullString
	TermSearch sql.NullString
}
