// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package people

import (
	"context"
)

const countPeople = `-- name: CountPeople :one
SELECT COUNT(1) FROM people
`

func (q *Queries) CountPeople(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPeople)
	var count int64
	err := row.Scan(&count)
	return count, err
}
