// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countPeople = `-- name: CountPeople :one
SELECT COUNT(1) FROM people
`

func (q *Queries) CountPeople(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPeople)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findPerson = `-- name: FindPerson :one
SELECT id, nickname, name, birthdate, stack FROM people WHERE id = $1
`

type FindPersonRow struct {
	ID        string
	Nickname  string
	Name      string
	Birthdate time.Time
	Stack     sql.NullString
}

func (q *Queries) FindPerson(ctx context.Context, id string) (FindPersonRow, error) {
	row := q.db.QueryRowContext(ctx, findPerson, id)
	var i FindPersonRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Name,
		&i.Birthdate,
		&i.Stack,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :exec
INSERT INTO people (
    id, nickname, name, birthdate, stack
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertPersonParams struct {
	ID        string
	Nickname  string
	Name      string
	Birthdate time.Time
	Stack     sql.NullString
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.ExecContext(ctx, insertPerson,
		arg.ID,
		arg.Nickname,
		arg.Name,
		arg.Birthdate,
		arg.Stack,
	)
	return err
}
